admin_auth/lib/pete_web/router.ex
defmodule PeteWeb.Router do
  use PeteWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :with_session do
    plug Pete.Auth.Pipeline
    plug Pete.Auth.CurrentUser
  end

  pipeline :login_required do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :admin_required do
    plug Pete.Auth.CheckAdmin
  end

  scope "/", PeteWeb do
    pipe_through [:browser, :with_session]

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    scope "/admin" do
      pipe_through [:admin_required]

      resources "/", AdminController, only: [:index]
    end
  end
end

admin_auth/lib/pete/user.ex
defmodule Pete.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Pete.User

  schema "users" do
    field :email, :string
    field :name, :string
    field :is_admin, :boolean, default: false
    field :password, :string, virtual: true
    field :password_hash, :string

    timestamps()
  end

  @required_fields ~w(email)a
  @optional_fields ~w(name is_admin)a
  def changeset(%User{} = user, attrs \\ %{}) do
    user
    |> cast(attrs, @required_fields ++ @optional_fields)
    |> validate_required(@required_fields)
    |> unique_constraint(:email)
  end

  def registration_changeset(struct, params) do
    struct
    |> changeset(params)
    |> cast(params, ~w(password)a, [])
    |> validate_length(:password, min: 6, max: 100)
    |> hash_password
  end

  defp hash_password(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true,
                      changes: %{password: password}} ->
        put_change(changeset,
                   :password_hash,
                   Comeonin.Bcrypt.hashpwsalt(password))
      _ ->
        changeset
    end
  end
end

admin_auth/lib/pete_web/controllers/admin_controller.ex
defmodule PeteWeb.AdminController do
  use PeteWeb, :controller

  def index(conn, _) do
    render conn, "index.html"
  end
end

admin_auth/lib/pete_web/views/admin_view.ex
defmodule PeteWeb.AdminView do
  use PeteWeb, :view
end

admin_auth/lib/pete_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Pete!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if @current_user do %>
              <li><%= @current_user.email %> (<%= @current_user.id %>)</li>
              <li>
                <%= link "Sign out", to: session_path(@conn, :delete, @current_user), method: "delete" %>
              </li>
              <%= if @current_user.is_admin do %>
                <li><%= link "Admin Dashboard", to: admin_path(@conn, :index)  %></li>
              <% end %>
            <% else %>
              <li>
                <%= link "Register", to: user_path(@conn, :new) %>
              </li>
              <li>
                <%= link "Sign in", to: session_path(@conn, :new) %>
              </li>
            <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>